### ISSUE TITLE
Issues about obtaining ICCAD-2012 contest benchmarks

### ISSUE THREAD

**Issue by WindVisionQAQ** [sumedhachugh/Lithography-Hotspot-Detection#1]
Hi, I've read your codes and very curious about the lithogrpahic hotspot detection issue. But I wonder where I can download the original ICCAD-2012 contest benchmarks because the original website (http://cad-contest.cs.nctu.edu.tw/CAD-contest-at-ICCAD2012/) is down somehow. Could you please tell me where I can obtain the dataset/benchmarks? Thanks!

**Comment by sumedhachugh** [comment]
Hi,
I obtained the dataset from the following link 
http://appsrv.cse.cuhk.edu.hk/~hyyang/files/iccad-official.tgz
Unfortunately, it is not working anymore. If there is some other way I can help you with this, let me know

**Comment by WindVisionQAQ** [comment]
> Hi,
> I obtained the dataset from the following link
> http://appsrv.cse.cuhk.edu.hk/~hyyang/files/iccad-official.tgz
> Unfortunately, it is not working anymore. If there is some other way I can help you with this, let me know


Hi, I appreciate your help and reply.

Considering the URL you provide, I've already posted an issue in the github page https://github.com/phdyang007/dlhsd and I'm waiting for the reply. Meanwhile, I wonder if you have a downloaded copy and if you do whether you can send me through mail or other ways within your reach. My Email address is luisliuzijie@foxmail.com.  Thanks.

**Comment by sumedhachugh** [comment]
Hey, 
Please check your email.
Hope it resolves the issue.

**Comment by sumedhachugh** [comment]
> > Hi,
> > I obtained the dataset from the following link
> > http://appsrv.cse.cuhk.edu.hk/~hyyang/files/iccad-official.tgz
> > Unfortunately, it is not working anymore. If there is some other way I can help you with this, let me know
> 
> Hi, I appreciate your help and reply.
> 
> Considering the URL you provide, I've already posted an issue in the github page https://github.com/phdyang007/dlhsd and I'm waiting for the reply. Meanwhile, I wonder if you have a downloaded copy and if you do whether you can send me through mail or other ways within your reach. My Email address is [luisliuzijie@foxmail.com](mailto:luisliuzijie@foxmail.com). Thanks.

Hey,
Please check your email.
Hope it resolves the issue.

**Comment by bhchoi98** [comment]
Hi, I've read your codes. I want to try some similar experiment to yours, but both ICCAD-2012 contest website and the link you provided are not working anymore. If you have a downloaded copy, would you mind sending it through Email? 
My Email address is bhchoi9883@gmail.com. I would appreciate any help. Thanks.

**Comment by Feixilu** [comment]
Hi, I've read your codes. Your ViT method show beautiful performance. I want to try some experiment about hotspot detection, and I face the same problem, both ICCAD-2012 contest website and the link you provided are not working anymore. Would you mind sending it to my Email?
My Email address is cxhwl2021@gmail.com. I would appreciate any help. Thanks.

**Comment by Mars-122** [comment]
Hi,
I have been through your project related to lithographic hotspot detection which I found quite informative, helpful, and a great contribution to this field. Mam, can you please send the original ICCAD 2012 dataset throughemail:contact.sifat123@gmail.com
because I tried a lot to download it but the original website (http://cad-contest.cs.nctu.edu.tw/CAD-contest-at-ICCAD2012/) is down somehow. Thanks

**Comment by sumedhachugh** [comment]
https://drive.google.com/file/d/1In9dr5kaAXbflTDn9uUZR1yDHplWnnU4/view

Link for dataset

**Comment by Mars-122** [comment]
Thank you so much Mam.

**Comment by sumedhachugh** [comment]
You’re welcome ☺️

**Comment by 1574300748** [comment]
> https://drive.google.com/file/d/1In9dr5kaAXbflTDn9uUZR1yDHplWnnU4/view
> 
> 数据集的链接

非常感谢

**Comment by zbj2008cn** [comment]
http://archive.sigda.org/dac2012/contest/dac2012_contest_benchmarks.html

**Comment by EngrNor** [comment]
Dear madam , hopefully you are good, I read your paper work ViT created great results , i want to know about information related to dataset how they can use ?please help me ,
Noor

**Comment by Duducoco** [comment]
Hello, I am very interested in your work. I downloaded the dataset from the previous link, but there is only a subset of the test set without hotspot labels. I cannot use such data for model training. Could you please provide other subsets? Thank you very much.
