### ISSUE TITLE
Lithography Hotspot dataset

### ISSUE THREAD

**Issue by amanraj2000** [sumedhachugh/Lithography-Hotspot-Detection#2]
Hi,
 I have recently visited your github. I am looking for the iccad 2012 benchmark dataset but somehow the link is not working. If you could just mail me the dataset to amanraj10396@gmail.com  , it will be very helpful.

Hoping for a positive reply.

**Comment by sumedhachugh** [comment]
Hi Aman,

PFB my drive's link for the dataset.

https://drive.google.com/file/d/1In9dr5kaAXbflTDn9uUZR1yDHplWnnU4/view

I guess it is accessible to all.
But Just in case you are not able to access it, please let me know.
Also, I have mailed this to ***@***.*** this email id, on GitHub
its showing as a different one so replying here as well

Regards,
Sumedha
